### ISSUE TITLE
Output PNG files gets the wrong size / content 

### ISSUE THREAD

**Issue by breakin** [MomentsInGraphics/BlueNoise#1]
Repro step:
* I've done pip install numpy scipy matplotlib pypng
* I called GenerateBlueNoiseDatabase(range(1), 32, 32, range(1,1), 1.9) in BlueNoise.py
* I'm using Windows 10. Tried python 2.7 and 3.8.0.

Problem:
* The LDR-texture that comes out is not square, it has a fourth of the intended width and has the wrong content too

All other attempts at saving images using StoreNoiseTextureLDR  gets me the same issue. It seems like the np.dstack is ignored or something like that.

My questions:
* Is the pypng the right import for the png module?
* Has your script ever been tested on Windows?

If I add the code below to the end of StoreNoiseTextureLDR it seems to work on my computer:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
w = Texture.shape[1]
h = Texture.shape[0]
SaveTexture = np.zeros((h, w * 4), dtype = np.uint8)

for y in range(h):
	for x in range(w):
		for c in range(4):
			SaveTexture[y, x * 4 + c] = Texture[y, x, c]

# Save the image
png.from_array(SaveTexture,"RGBA;8").save(OutputPNGFilePath);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Thanks for the nice noise textures!

**Comment by MomentsInGraphics** [comment]
Apparently the pypng interface changed a bit at some point in the past three years. It should be fixed now. Thanks for the report.
